# This playbook install the prosody (http://prosody.im) xmpp server.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install prosody package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - prosody

- name: default prosody configuration file
  template: src=files/prosody-config.j2
            dest=/etc/prosody/prosody.cfg.lua
            owner=root
            group=root
            mode=0644

- name: download additional prosody modules
  get_url: url=http://prosody.im/files/{{ item }}.lua
           dest=/usr/lib64/prosody/modules/{{ item }}.lua
           mode=0775
  with_items:
    - mod_listusers

#- name: download additional prosody modules
#  get_url: url=http://prosody-modules.googlecode.com/hg/{{ item }}/{{ item }}.lua
#           dest=/usr/lib64/prosody/modules/{{ item }}.lua
#           mode=0775          
#  with_items:
#    - mod_broadcast
#    - mod_block_registrations

#- name: add xmpp users
#  command: /usr/bin/prosodyctl register {{ item }}@10.0.0.65 mypassword
#  with_items:
#    - admin
#    - bob
#    - alice
#    - testbench

- name: configure firewall, allow traffic to different ports
  firewalld: port={{ item }}/tcp
             permanent=true
             state=enabled
  with_items:
     - 5222
     - 5269
     - 5582

- name: start prosody
  service: name=prosody
           state=running
           enabled=yes
