# This playbook install a telnet server.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install telnet package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - telnet-server

- name: configure firewall, allow telnet traffic
  firewalld: service=telnet
             permanent=true
             state=enabled

- name: start and enable the telnet service
  service: name=telnet.socket
           state=running
           enabled=yes
