# This playbook contains all tasks to setup a Fedora Security Lab test bench as
# virtual machine.
#
# Copyright (c) 2013-2018 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: sudo ansible-playbook fsl-test-bench/local-setup.yml --connection=local
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive.yml
    - variables/local.yml
    - variables/containers.yml

  tasks:
# Virtual machine setup

# Setup Test bench connection
    - include: tasks/auth-key.yml

# Runtime changes aren't detected
    - name: setup ansible host file
      lineinfile:
        dest: /etc/ansible/hosts
        regexp: '^'
        insertafter: '127.0.0.1'
        line: '127.0.0.1\n\n[fsl-tb]\n{{ ip }}'

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
