# This playbook contains tasks to perform on a fresh Fedora installation to
# create a Fedora Security Lab Test bench. 
#
# Copyright (c) 2013-2016 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: sudo ansible-playbook all-in-one.yml -f 10
# 
---
- hosts: fsl-tb
  user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive.yml
    - variables/containers.yml

  tasks:
# Common tasks
################################################################################
    - include: tasks/preparation.yml
    - include: tasks/motd.yml
#    - include: tasks/hosts.yml
#    - include: tasks/users.yml

# FSL Test bench specific stuff
################################################################################
    - include: tasks/web-servers/lighttpd.yml
    - include: tasks/web-interface.yml

# Services
################################################################################
## Web servers
#    - include: tasks/web-servers/apache.yml
#    - include: tasks/web-servers/cherokee.yml
#    - include: tasks/web-servers/nginx.yml
    - include: tasks/web-servers/tomcat.yml
#    - include: tasks/web-servers/pywebserve.yml
#    - include: tasks/web-servers/nodejs.yml
#    - include: tasks/web-servers/mongoose.yml
#    - include: tasks/web-servers/darkhttpd.yml
#    - include: tasks/web-servers/droopy.yml
## Database server
#    - include: tasks/db-servers/mysql.yml # replaced by MariaDB playbook
#    - include: tasks/db-servers/mariadb.yml
#    - include: tasks/db-servers/mongodb.yml
## FTP server
#    - include: tasks/ftp-servers/vsftpd.yml
## Misc servers
#    - include: tasks/misc-servers/openssh.yml
#    - include: tasks/misc-servers/dropbear.yml
#    - include: tasks/misc-servers/tftp.yml
#    - include: tasks/misc-servers/telnet.yml
    - include: tasks/misc-servers/cups.yml
#    - include: tasks/misc-servers/openvpn-static.yml
#    - include: tasks/misc-servers/xrdp.yml
#    - include: tasks/misc-servers/mosquitto.yml
    - include: tasks/misc-servers/snmp.yml
## File servers
#    - include: tasks/file-servers/samba.yml
#    - include: tasks/file-servers/nfs.yml  # Needs manual start
## Mail server
#    - include: tasks/mail-servers/postfix.yml
#    - include: tasks/mail-servers/dovecot.yml

# Helpers
################################################################################
#    - include: tasks/helpers/log-system.yml
#    - include: tasks/helpers/phpinfo.yml
#    - include: tasks/helpers/cockpit.yml
# Shell Detector is not able to handle the present amount of files. Memory?
#    - include: tasks/helpers/php-shell-detector.yml
    - include: tasks/helpers/linfo.yml
#    - include: tasks/helpers/phpmyadmin.yml
#    - include: tasks/helpers/phpldapadmin.yml
#    - include: tasks/helpers/phpliteadmin.yml
#    - include: tasks/helpers/phpmoadmin.yml
    - include: tasks/helpers/pcc.yml
# Common Gateway Interface (CGI)
################################################################################
    - include: tasks/cgi/cgi.yml
## C (default)
    - include: tasks/cgi/time.yml
## Python
    - include: tasks/cgi/time-py.yml
## Bash
    - include: tasks/cgi/env-sh.yml
    - include: tasks/cgi/system-sh.yml
## Perl
    - include: tasks/cgi/time-pl.yml

# Vulnerable Web Application
################################################################################
    - include: tasks/apps/mcir.yml
#    - include: tasks/apps/sqli.yml
#    - include: tasks/apps/bwapp.yml
#    - include: tasks/apps/dvwa.yml
#    - include: tasks/apps/hackademic.yml
#    - include: tasks/apps/xssed.yml
#    - include: tasks/apps/bricks.yml

# Honeypots
################################################################################
#    - include: tasks/honeypots/honeyd.yml

# Shells
################################################################################
    - include: tasks/shells/b374k.yml
    - include: tasks/shells/dnashell.yml
    - include: tasks/shells/phpshell.yml
#    - include: tasks/shells/ajaxshell.yml
#    - include: tasks/shells/wso.yml
# Common tasks
################################################################################
#    - include: tasks/cleanup.yml

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
