# This playbook install the cherokee webserver (http://cherokee-project.com/).
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install cherokee package
  yum: pkg={{ item }}
       state=present 
  with_items:
    - cherokee

- name: run cherokee on 8008
  lineinfile: dest=/etc/cherokee/cherokee.conf
              regexp='^server!bind!1!port = 80'
              insertafter='^server!bind!1!port = 80'
              line='server!bind!1!port = 8008'
              state=present

- name: start cherokee
  service: name=cherokee
           state=running
           enabled=yes 

- name: configure firewall, allow traffic to port 8008
  firewalld: port=8008/tcp
             permanent=true
             state=enabled

- name: remove cherokee default file
  file: path=/var/www/cherokee/{{ item }}
        state=absent
  with_items:
    - index.html
    - images

- name: install a default index.html file
  template: src=files/website/default.j2 
            dest=/var/www/cherokee/index.html
            owner=root
            group=root
            mode=0644
